version: "3.9"

services:
  client:
    build: ./client
    container_name: next-client
    restart: always
    dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API=https://api.trymemento.app
      - UPLOADTHING_TOKEN=${UPLOADTHING_TOKEN}
    depends_on:
      - server

  server:
    build: ./server
    container_name: express-server
    restart: always
    dockerfile: Dockerfile
    expose:
      - "4000"
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}